// AppState.jsx
// Global state for the Full App mockup — router, language, theme, tweaks.
// All state lives in a single context so device frames stay in sync when
// the user switches language or navigates.

const { createContext, useContext, useState, useCallback, useMemo, useEffect } = React;

// ─── Language pack (subset — enough for the visible UI) ──────────────
// Full catalog lives in gando-ai_Design/src/translations.ts. We mirror the
// keys this mockup actually renders.
const STRINGS = {
  en: {
    appName: "Gando",
    beta: "Public Beta",
    loginWithGoogle: "Continue with Google",
    heroTitle: "Build apps with Gando AI.",
    heroSubtitle: "The modern app builder for Africa. Describe your vision in your native tongue and watch it come to life.",

    dashboardNav: "Dashboard",
    projectsNav: "My Projects",
    assetsNav: "Language Assets",
    settingsNav: "Settings",
    teamHubLabel: "Team Hub",
    docsNav: "Docs",
    statusNav: "System Status",
    signOut: "Sign Out",
    searchPlaceholder: "Search Gando…",
    newProject: "New Project",
    projectsCreatedLabel: "Projects Created",
    workspace: "Workspace",

    gandoViewTitle: "Good morning, Amadou.",
    gandoViewSubtitle: "Build apps in your African language.",
    projectsLabel: "Projects",
    appsBuiltLabel: "Apps Built",
    activeSiteBuildsLabel: "Active Site Builds",
    viewAllLabel: "View all",
    projectCompletionLabel: "Project Completion",
    completionSubtitle: "Overall progress across your Gando projects.",
    tokenUsageLabel: "Tokens Used",
    tokenResetHint: "Utilization within healthy bounds.",
    healthyLabel: "Healthy",
    appPerformanceLabel: "App Performance",
    excellentLabel: "Excellent",
    latencyLabel: "Latency",
    uptimeLabel: "Uptime",
    runtimeLabel: "Runtime",
    totalFlowLabel: "Total Flow",
    appsGeneratedLabel: "Apps Generated",
    totalPromptsLabel: "Total Prompts",

    chatWelcome: "What will you build today?",
    chatSubtitle: "Describe your vision. Gando handles the rest.",
    inputPlaceholder: "Describe your app…",
    generating: "Gando is building…",
    suggestionEcom: "E-commerce store",
    suggestionLearning: "Language learning",
    suggestionCommunity: "Community hub",

    preview: "Preview",
    code: "Code",
    download: "Download",
    share: "Share",
    deploy: "Deploy",

    // Projects page
    projectsPageTitle: "My Projects",
    projectsPageSubtitle: "All your projects generated by Gando AI",
    searchProjectsPlaceholder: "Search projects…",

    // Status page
    statusPageTitle: "System Status",
    statusPageSubtitle: "Real-time monitoring of Gando AI services",
    statusServer: "Server",
    statusAI: "AI Model",
    statusFirebase: "Database",
    statusOperational: "Operational",
    statusLastChecked: "Last checked",

    // Docs
    docsPageTitle: "Gando Documentation",
    docsPageSubtitle: "Everything you need to build with Gando AI",
  },

  fr: {
    appName: "Gando",
    beta: "Bêta Publique",
    loginWithGoogle: "Continuer avec Google",
    heroTitle: "Créez des apps avec Gando AI.",
    heroSubtitle: "Le constructeur d'applications moderne pour l'Afrique. Décrivez votre vision dans votre langue maternelle.",

    dashboardNav: "Tableau de bord",
    projectsNav: "Mes Projets",
    assetsNav: "Ressources Linguistiques",
    settingsNav: "Paramètres",
    teamHubLabel: "Équipe",
    docsNav: "Documentation",
    statusNav: "État du Système",
    signOut: "Déconnexion",
    searchPlaceholder: "Rechercher…",
    newProject: "Nouveau Projet",
    projectsCreatedLabel: "Projets Créés",
    workspace: "Espace de travail",

    gandoViewTitle: "Bonjour, Amadou.",
    gandoViewSubtitle: "Créez des applications dans votre langue.",
    projectsLabel: "Projets",
    appsBuiltLabel: "Apps Créées",
    activeSiteBuildsLabel: "Projets Actifs",
    viewAllLabel: "Voir tout",
    projectCompletionLabel: "Avancement des Projets",
    completionSubtitle: "Progression globale de vos projets.",
    tokenUsageLabel: "Tokens Utilisés",
    tokenResetHint: "Utilisation dans les limites normales.",
    healthyLabel: "Sain",
    appPerformanceLabel: "Performance",
    excellentLabel: "Excellent",
    latencyLabel: "Latence",
    uptimeLabel: "Disponibilité",
    runtimeLabel: "Runtime",
    totalFlowLabel: "Flux Total",
    appsGeneratedLabel: "Apps Générées",
    totalPromptsLabel: "Total Prompts",

    chatWelcome: "Que vas-tu construire aujourd'hui ?",
    chatSubtitle: "Décrivez votre vision. Gando s'occupe du reste.",
    inputPlaceholder: "Décrivez votre application…",
    generating: "Gando construit…",
    suggestionEcom: "Boutique en ligne",
    suggestionLearning: "Apprentissage",
    suggestionCommunity: "Communauté",

    preview: "Aperçu",
    code: "Code",
    download: "Télécharger",
    share: "Partager",
    deploy: "Déployer",

    projectsPageTitle: "Mes Projets",
    projectsPageSubtitle: "Tous vos projets générés par Gando AI",
    searchProjectsPlaceholder: "Rechercher un projet…",

    statusPageTitle: "État du Système",
    statusPageSubtitle: "Surveillance en temps réel de Gando AI",
    statusServer: "Serveur",
    statusAI: "Modèle IA",
    statusFirebase: "Base de données",
    statusOperational: "Opérationnel",
    statusLastChecked: "Dernière vérification",

    docsPageTitle: "Documentation Gando",
    docsPageSubtitle: "Tout ce que vous devez savoir pour utiliser Gando AI",
  },

  "ff-adlm": {
    appName: "𞤘𞤢𞤲𞤣𞤮",
    beta: "𞤘𞤢𞤲𞤣𞤮 𞤄𞤫𞤼𞤢",
    loginWithGoogle: "𞤔𞤮𞤳𞥆𞤵 𞤫 𞤘𞤵𞥅𞤺𞤮𞤤",
    heroTitle: "𞤃𞤢𞤸𞤵 𞤢𞤨𞥆𞤧 𞤫 𞤘𞤢𞤲𞤣𞤮.",
    heroSubtitle: "𞤃𞤢𞤸𞤮𞥅𞤱𞤮 𞤢𞤨𞥆𞤧 𞤶𞤢𞤥𞤢𞥄𞤲𞤵 𞤲𞤺𞤢𞤥 𞤀𞤬𞤪𞤭𞤳𞤢.",

    dashboardNav: "𞤚𞤢𞤩𞤤𞤮",
    projectsNav: "𞤆𞤮𞤪𞤮𞤶𞤫𞥅𞤶𞤭",
    assetsNav: "𞤑𞤢𞥄𞤤𞤫𞥅𞤶𞤭",
    settingsNav: "𞤚𞤫𞤩𞥆𞤫",
    teamHubLabel: "𞤒𞤫𞤴𞥆𞤢𞤥",
    docsNav: "𞤀𞤬𞤪𞤢𞤥𞤪𞤫",
    statusNav: "𞤅𞤢𞤻𞤮𞤪𞤫",
    signOut: "𞤒𞤢𞤤𞤼𞤵𞤯𞤮",
    searchPlaceholder: "𞤕𞤫𞥅𞤰𞤭…",
    newProject: "𞤆𞤮𞤪𞤮𞤶𞤫 𞤳𞤫𞤧𞤮",
    projectsCreatedLabel: "𞤆𞤮𞤪𞤮𞤶𞤫𞥅𞤶𞤭 𞤐𞤢𞤥𞤥𞤭𞤯𞤭",
    workspace: "𞤐𞤣𞤭𞤫𞤥𞤥𞤢",

    gandoViewTitle: "𞤔𞤢𞤥 𞤶𞤢𞤥, 𞤀𞤥𞤢𞤣𞤵.",
    gandoViewSubtitle: "𞤃𞤢𞤸𞤵 𞤢𞤨𞥆 𞤯𞤫𞤲𞤯𞤢𞤤 𞤥𞤢𞥄𞤯𞤢.",
    projectsLabel: "𞤆𞤮𞤪𞤮𞤶𞤫𞥅𞤶𞤭",
    appsBuiltLabel: "𞤀𞤨𞥆𞤧 𞤃𞤢𞤸𞤢𞥄𞤯𞤭",
    activeSiteBuildsLabel: "𞤆𞤮𞤪𞤮𞤶𞤫𞥅𞤶𞤭 𞤑𞤭𞤸𞤯𞤵𞤯𞤭",
    viewAllLabel: "𞤖𞤮𞤤𞤼𞤭 𞤸𞤫𞤯𞤯𞤢𞤲",
    projectCompletionLabel: "𞤆𞤮𞤪𞤮𞤶𞤫 𞤏𞤢𞤼𞤵𞤣𞤫",
    completionSubtitle: "𞤆𞤮𞤪𞤮𞤶𞤫𞥅𞤶𞤭 𞤸𞤢𞤲𞤳𞤭𞤣𞤫.",
    tokenUsageLabel: "𞤚𞤮𞤳𞤫𞤲 𞤁𞤢𞤩𞤦𞤮𞤪𞤣𞤫",
    tokenResetHint: "𞤚𞤮𞤳𞤫𞤲 𞤯𞤵𞤥.",
    healthyLabel: "𞤌𞤲𞤣𞤢𞤥",
    appPerformanceLabel: "𞤃𞤢𞤸𞤮𞥅𞤱𞤮",
    excellentLabel: "𞤇𞤫𞥅𞤯𞤢𞤲",
    latencyLabel: "𞤔𞤢𞥄𞤤𞤫𞤤",
    uptimeLabel: "𞤒𞤨𞤼𞤭𞤥",
    runtimeLabel: "𞤚𞤢𞤩𞤤𞤮",
    totalFlowLabel: "𞤸𞤫𞤯𞤯𞤢𞤲",
    appsGeneratedLabel: "𞤀𞤨𞥆𞤧 𞤃𞤢𞤸𞤢𞥄𞤯𞤭",
    totalPromptsLabel: "𞤖𞤢𞥄𞤤𞤵 𞤸𞤫𞤯𞤯𞤢𞤲",

    chatWelcome: "𞤑𞤮 𞤸𞤮𞤲𞤯𞤵𞤥 𞤥𞤢𞤸𞤮𞤼𞤢𞥄?",
    chatSubtitle: "𞤖𞤢𞥄𞤤𞤵 𞤳𞤮 𞤲𞤮𞤼𞥆𞤢𞥄. 𞤘𞤢𞤲𞤣𞤮 𞤲𞤮𞤼𞥆𞤢𞥄.",
    inputPlaceholder: "𞤖𞤢𞥄𞤤𞤵 𞤢𞤨𞥆 𞤥𞤢𞥄𞤯𞤢…",
    generating: "𞤘𞤢𞤲𞤣𞤮 𞤲𞤮 𞤥𞤢𞤸𞤢…",
    suggestionEcom: "𞤜𞤲𞤲𞤦𞤮𞤱𞤢",
    suggestionLearning: "𞤔𞤢𞤲𞤺𞤵𞤺𞤮",
    suggestionCommunity: "𞤘𞤵𞤩𞥆𞤵",

    preview: "𞤖𞤮𞤤𞥆𞤭𞤪𞤣𞤫",
    code: "𞤑𞤮𞥅𞤣",
    download: "𞤔𞤫𞤩𞥆𞤵",
    share: "𞤖𞤮𞥅𞤪𞤫",
    deploy: "𞤖𞤵𞥅𞤼𞤮𞤪",

    projectsPageTitle: "𞤆𞤮𞤪𞤮𞤶𞤫𞥅𞤶𞤭 𞤢𞤥",
    projectsPageSubtitle: "𞤆𞤮𞤪𞤮𞤶𞤫𞥅𞤶𞤭 𞤣𞤮 𞤲𞤢𞤥𞤥𞤭𞤯𞤭",
    searchProjectsPlaceholder: "𞤕𞤫𞥅𞤰𞤭…",

    statusPageTitle: "𞤅𞤭𞤧𞤼𞤫𞤥 𞤅𞤢𞤻𞤮𞤪𞤫",
    statusPageSubtitle: "𞤅𞤢𞤻𞤮𞤪𞤫 𞤘𞤢𞤲𞤣𞤮",
    statusServer: "𞤐𞤵𞤲𞤪𞤵",
    statusAI: "𞤘𞤢𞤲𞤣𞤮 𞤀𞤋",
    statusFirebase: "𞤁𞤢𞤼𞤢𞤦𞤢𞤧𞤫",
    statusOperational: "𞤒𞤫𞥅𞤲𞤯𞤭",
    statusLastChecked: "𞤕𞤫𞥅𞤰𞤢𞥄𞤯𞤭",

    docsPageTitle: "𞤀𞤬𞤪𞤢𞤥𞤪𞤫 𞤘𞤢𞤲𞤣𞤮",
    docsPageSubtitle: "𞤃𞤢𞤸𞤵 𞤢𞤨𞥆 𞤫 𞤘𞤢𞤲𞤣𞤮",
  },
};

// ─── Sample project data ──────────────────────────────────
const SAMPLE_PROJECTS = [
  { id: "p1", name: "Marché Bamako",       language: "French",  description: "E-commerce platform for artisan goods from Mali", progress: 100, createdAt: "2 days ago",  status: "live",    prompts: 18 },
  { id: "p2", name: "𞤔𞤢𞤲𞤺𞤵𞤺𞤮 𞤆𞤵𞤤𞤢𞤪",    language: "Fulani",  description: "Language learning app for Fulani speakers",        progress: 78,  createdAt: "5 days ago",  status: "building", prompts: 12 },
  { id: "p3", name: "Kilimo Connect",      language: "Swahili", description: "Farmer-to-buyer marketplace for East Africa",    progress: 45,  createdAt: "1 week ago",  status: "building", prompts: 7  },
  { id: "p4", name: "Owambe Events",       language: "Yoruba",  description: "Event booking platform for West African celebrations", progress: 92, createdAt: "2 weeks ago", status: "live",    prompts: 24 },
  { id: "p5", name: "Taxi Kano",           language: "Hausa",   description: "Ride-hailing app tailored to northern Nigeria", progress: 30,  createdAt: "3 weeks ago", status: "draft",    prompts: 4  },
  { id: "p6", name: "Dakar Delivery",      language: "Wolof",   description: "Hyper-local food delivery across Dakar",        progress: 100, createdAt: "1 month ago", status: "live",    prompts: 31 },
];

// ─── App State Context ───────────────────────────────────
const AppCtx = createContext(null);

const AppStateProvider = ({ children, initial = {} }) => {
  const [lang, setLang] = useState(initial.lang || "en");
  const [route, setRoute] = useState(initial.route || "dashboard");
  const [activeProject, setActiveProject] = useState(initial.activeProject || null);
  const [dashboardVariant, setDashboardVariant] = useState(initial.dashboardVariant || "cards");
  const [workspaceLayout, setWorkspaceLayout] = useState(initial.workspaceLayout || "split");
  const [chatState, setChatState] = useState(initial.chatState || "empty"); // empty | typing | generating | result

  const t = useMemo(() => STRINGS[lang] || STRINGS.en, [lang]);

  const value = useMemo(() => ({
    lang, setLang,
    route, setRoute,
    activeProject, setActiveProject,
    dashboardVariant, setDashboardVariant,
    workspaceLayout, setWorkspaceLayout,
    chatState, setChatState,
    t,
    projects: SAMPLE_PROJECTS,
  }), [lang, route, activeProject, dashboardVariant, workspaceLayout, chatState, t]);

  return h(AppCtx.Provider, { value }, children);
};

const useApp = () => {
  const ctx = useContext(AppCtx);
  if (!ctx) throw new Error("useApp() must be inside AppStateProvider");
  return ctx;
};

// ─── Language labels ─────────────────────────────────────
const LANG_META = {
  en:       { short: "EN", full: "English",        isAdlam: false, native: "English" },
  fr:       { short: "FR", full: "Français",       isAdlam: false, native: "Français" },
  "ff-adlm": { short: "𞤘", full: "𞤆𞤵𞤤𞤢𞥄𞤪 (ADLaM)",   isAdlam: true,  native: "𞤆𞤵𞤤𞤢𞥄𞤪" },
};

Object.assign(window, {
  AppCtx, AppStateProvider, useApp, LANG_META, STRINGS, SAMPLE_PROJECTS,
});
